#theme: jekyll-theme-minimalls
baseURL: "https://alexa.kangifaz.io/"
languageCode: "id-ID"
title: "Alexa Documentation"
theme: "lotusdocs"

params:
  mainSections:
    - "docs"
  docs: true

markup:
  highlight:
    style: "monokai"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Docs"
      url: "/docs/"
      weight: 2
